---
title: "R Notebook"
output: html_notebook
---
# Imports

```{r}
library(DataComputing)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(writexl)
library(bizdays)

```

```{r}
library(readxl)
Frozen2 <- read_excel("C:/Users/smazeski/Desktop/WinterData/Frozen.xlsx")
Refridgerate <- read_excel("C:/Users/smazeski/Desktop/WinterData/Refridgerate.xlsx")
vieworder2 <- read_excel("C:/Users/smazeski/Desktop/WinterData/vieworder2.xlsx")
salesanalysis <- read_excel("C:/Users/smazeski/Desktop/WinterData/salesanalysis.xlsx")

```



```{r}

head(vieworder2)
```


```{r}
head(salesanalysis)

```

```{r}
colnames(salesanalysis)
```

```{r}
colnames(vieworder2)
```
```{r}
head(Refridgerate)

```
```{r}
head(Frozen2)

```
```{r}
Refridgerate <- Refridgerate %>% mutate(Product = "R")

```
```{r}
Frozen2 <- Frozen2 %>% mutate(Product = "F")
head(Frozen2)


```
```{r}
products <- rbind(Frozen2, Refridgerate)

tail(products)
```




```{r}
Merged <- merge(salesanalysis, vieworder2, by = "SalesNum")
Merged2<- full_join(Merged, products, by = "ItemID")

```

```{r}
Merged2$Product[is.na(Merged2$Product)] = 'O'
colnames((Merged2))



```


```{r}

Merged_Cut <- Merged2 %>% select(SalesNum, Invoice, SalesNum, Category, ShipToState, ItemID, Quantity, DateOrdered, Date, Shipped, ItemID, Product, AddressType)

```


#Here we see from the data that DateShipped is the date in which ALL items are completed shipping. Date.y is the order date and I will change names accordingly

```{r}
names(Merged_Cut)[names(Merged_Cut) == "DateOrdered"] <- "OrderDate"
names(Merged_Cut)[names(Merged_Cut) == "Date"] <- "FullyShipped"
names(Merged_Cut)[names(Merged_Cut) == "Shipped"] <- "InvoiceShipped"

head(Merged_Cut, 30)

```

```{r}

Merged_Cut <- Merged_Cut %>% mutate(DaysDelayed =as.integer( difftime(InvoiceShipped, OrderDate, unit = "days")))
Merged_Cut <- Merged_Cut %>% filter(DaysDelayed < 8)
head(Merged_Cut,10)
```



```{r}
Merged_Cut <- Merged_Cut %>% mutate(OrderDayoftheWeek = wday(OrderDate))
Merged_Cut <- Merged_Cut %>% mutate(ShipmentDayoftheWeek = wday(InvoiceShipped))

Merged_Cut$DaysDelayed <- with(Merged_Cut, ifelse(OrderDayoftheWeek == 1 & Product != 'O' & DaysDelayed != 0, DaysDelayed - 1, DaysDelayed))

Merged_Cut$DaysDelayed <- with(Merged_Cut, ifelse(OrderDayoftheWeek == 7 & AddressType == 'R' & Product != 'O'& DaysDelayed != 0, DaysDelayed - 1, DaysDelayed))

Merged_Cut$DaysDelayed <- with(Merged_Cut, ifelse(OrderDayoftheWeek == 7 & AddressType == 'C'& Product != 'O'& DaysDelayed != 0, DaysDelayed - 1, DaysDelayed))

view(Merged_Cut)

```
```{r}
MergedSplit <- Merged_Cut %>% filter(AddressType == 'C' | AddressType == 'R') %>%group_by(Product, AddressType, OrderDayoftheWeek) %>% summarise(AvgDayShip = mean(DaysDelayed))


ggplot(data=MergedSplit,aes(x=OrderDayoftheWeek,y=AvgDayShip))+geom_point(size = 3)+aes(colour=Product, shape = AddressType)#+facet_wrap(~Product,ncol=4) 
#view(Merged_Cut)
```

```{r}


view(MergedSplit)
```




```{r}
#write_xlsx(x=Merged_Cut, path="Cleaned_Data_MAIN.csv",col_names=T)
```


```{r}

DidNotMakeWedCut <- Merged_Cut %>% filter(OrderDayoftheWeek == 4,DaysDelayed== 5)
head(DidNotMakeWedCut)
#view(DidNotMakeWedCut)
```


```{r}


AddressSplit <- Merged_Cut %>% group_by(AddressType) %>% summarise(AddressTypeForOrder=n())
AddressSplit
```


```{r}

#Products bought from 105
# F = Frozen
# O = Other
# R = Refridgerated
ProductsBought<- Merged_Cut %>% group_by(Product) %>% summarise(ProductTypeSpred=n())
ProductsBought

```


```{r}

#Delays_Spread <- Merged_Cut %>% group_by(DaysDelayed, AddressType, Product) %>% summarise(DaysDelayedCount=n())
#View(Delays_Spread)


# Consider this: 

```

```{r}

# States based on https://www.webstaurantstore.com/newwebadmin/mvc/logistics:warehouseTransitTimes/ Zones 1&2
# By state, these orders have the following attributes:::


# State within the 1-2 day window
# Ordered on Wednesday
# Frozen or Regridgerated Goods
# Were held for 5 days, until the following Monday, though could have arrived by Saturday

StateSpread <- Merged_Cut %>% group_by(ShipToState) %>% mutate(Zone = ifelse(ShipToState == "NY" | ShipToState == "PA"| ShipToState == "ME"| ShipToState == "VT"| ShipToState == "NH"| ShipToState == "MA"| ShipToState == "RI"| ShipToState == "CT"| ShipToState == "NJ"| ShipToState == "DE"| ShipToState == "MD"| ShipToState == "WV"| ShipToState == "VA"| ShipToState == "MI"| ShipToState == "OH"| ShipToState == "MI"| ShipToState == "IN"| ShipToState == "IL"| ShipToState == "KY"| ShipToState == "TN"| ShipToState == "AL"| ShipToState == "NC"| ShipToState == "SC"| ShipToState == "GA"| ShipToState == "FL"| ShipToState == "DC", 2,
                                                               ifelse(ShipToState == "MS" | ShipToState == "LA"| ShipToState == "WI"| ShipToState == "IA"| ShipToState == "MO"| ShipToState == "OK"| ShipToState == "TX"| ShipToState == "MN"| ShipToState == "OK"| ShipToState == "KS"| ShipToState == "SD"| ShipToState == "ND" | ShipToState == "AR", 3,
                                                               ifelse(ShipToState == "NM" | ShipToState == "AZ"| ShipToState == "MT"| ShipToState == "WY"| ShipToState == "NE"| ShipToState == "CO", 4,
                                                               ifelse(ShipToState == "ID" | ShipToState == "OR"| ShipToState == "CA"| ShipToState == "UT"| ShipToState == "NV"| ShipToState == "WA", 5,
                                                               ifelse(ShipToState == "AK" | ShipToState == "HI",7, NA))))))

(StateSpread)

```
Sum of the above is 79 orders over two weeks of analyzing Wednesday data specifically

```{r}
StateSpread<- StateSpread %>% filter(ShipToState!='HI' & ShipToState!='AK')
MergedSplit2 <- StateSpread %>% filter(AddressType == 'C' | AddressType == 'R') %>%group_by(Product, AddressType, OrderDayoftheWeek, Zone) %>% summarise(AvgDayShip = mean(DaysDelayed))



#ggplot(data=MergedSplit,aes(x=OrderDayoftheWeek,y=AvgDayShip))+geom_point(size = 3)+aes(colour=Product, shape = AddressType)#+facet_wrap(~Product,ncol=4) 
ggplot(data=MergedSplit2,aes(x=OrderDayoftheWeek,y=AvgDayShip))+geom_point(size = 4)+aes(colour=Product, shape = AddressType)+facet_wrap(~Zone,ncol=4) 


```

```{r}

MergedSplit2
```

```{r}

MergedSplitCount <- StateSpread %>% filter(AddressType == 'C' | AddressType == 'R') %>%group_by(Product, AddressType, OrderDayoftheWeek, Zone) %>% summarise(CountTotal = n())
head(MergedSplitCount)
```
```{r}

# 105 Orders by Shipping Zone over a two week period

StateSpread %>% group_by(Zone) %>% summarise(ZoneCount = n())

```

```{r}
ggplot(data=MergedSplitCount,aes(x=OrderDayoftheWeek,y=CountTotal))+geom_point(size = 3)+aes(colour=Product, shape = AddressType)+facet_wrap(~Zone,ncol=4) 

```


```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```